version: '3'
services:
  backend:
    image: faavour/my-backend-image:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/todo
  frontend:
    image: faavour/my-frontend-image:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    
    