apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
spec:
  ports:
  - name: "3100"
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    service: backend