name: Continous Integration Pipeline
on:
   push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build image
      run: |
        docker build -t faavour/my-backend-image:v1 -f ./Backend/Dockerfile ./Backend
        docker build -t faavour/my-frontend-image:v1 -f ./Frontend/Dockerfile ./Frontend

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image to Docker Hub
      run: |
        docker push faavour/my-backend-image:v1
        docker push faavour/my-frontend-image:v1

  deploy:
    runs-on: ubuntu-latest

    


